#!/bin/bash
# ubuntu server 12.04 x64

apt-get update && apt-get -y upgrade && apt-get -y install wget build-essential libtool autoconf automake uuid-dev pkg-config

# Install ZeroMQ
cd /tmp
tar -zxvf zeromq-2.1.7.tar.gz
cd zeromq-2.1.7
./configure
make install
ldconfig

# Install JZMQ
cd /tmp
tar -zxvf jzmq.tar.gz
cd jzmq
./autogen.sh
./configure
touch src/classdist_noinst.stamp
cd src
javac -d . org/zeromq/*.java
cd ../
make
make install
ldconfig

# Install Storm

cd /tmp
tar -zxvf storm-0.9.0.tar.gz
mv storm-0.9.0 /usr/share/storm

# Cleanup

cd /
rm -r /tmp/*
apt-get -y purge build-essential libtool autoconf automake pkg-config
apt-get -y autoremove
